# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: PSLVirginia

# HTML Language setting
#lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
#plugins:
#  # Automatically fetch Medium follower count
#  - MediumFollowersCountPlugin:
#      username: zhgchgli
#  # Automatically fetch Github repo star count
#  - GithubRepoStarsCountPlugin:
#      - ZhgChgLi/ZMarkupParser
#      - ZhgChgLi/ZReviewTender
#      - ZhgChgLi/ZMediumToMarkdown
#      - ZhgChgLi/linkyee
plugins:
  - I18n:
      supported_langs: ["en", "es", "zh"]
      translations:
        Title:
          en: "PSL Virginia"
          es: "PSL Virginia"
          zh: "社会主义与解放党 弗吉尼亚"
        Name:
          en: "@PSLVirginia"
          es: "@PSLVirginia"
          zh: "@PSLVirginia"
        Tagline:
          en: "PSL Virginia is the branch of the Party for Socialism and Liberation based out of Richmond, Virginia and Norfolk, Virginia."
          es: "PSL Virginia es la rama del Partido por el Socialismo y la Liberación con sede en Richmond, Virginia, y Norfolk, Virginia."
          zh: "PSL Virginia 是“社会主义与解放党”（Party for Socialism and Liberation）的分支机构，总部位于弗吉尼亚州的里士满和诺福克。"

        Instagram:
          en: "Follow Us On Instagram"
          es: "Síguenos en Instagram"
          zh: "在Instagram上关注我们"
        Telegram:
          en: "Get updates on Telegram"
          es: "Recibe actualizaciones en Telegram"
          zh: "在 Telegram 上获取更新"
        Signal:
          en: "Get updates on Signal"
          es: "Recibe actualizaciones en Signal"
          zh: "在 Signal 上获取更新"
        RAADPetition:
          en: "Sign the RAAD Petition"
          es: "Firma la petición RAAD"
          zh: "签署 RAAD 请愿书"
        Report:
          en: "Report an Incident"
          es: "Reportar un incidente"
          zh: "报告事件"

# Google Analytics tracking id
#google_analytics_id:

# HTML Title
title: "PSL Virginia Linkyee"

# Avatar image path
avatar: "./images/PSLVA_Logo.svg"

# Name section text
#name: "@PSLVirginia"

# Tagline section text
tagline: >-
    {{vars.I18n['Tagline']}}

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-instagram"
      text: "{{vars.I18n['Instagram']}}"
      url: "https://www.instagram.com/pslvirginia"
      alt: "Instagram"
      title: "Instagram"
      target: "_blank"
#  - link:
#      icon: "fa-brands fa-square-whatsapp"
#      text: "{{vars.I18n['WhatsApp']}}"
#      url: "https://chat.whatsapp.com/J2JcvDaEDJ22ixOQOjUN3o"
#      alt: "Whatsapp"
#      title: "Whatsapp"
#      target: "_blank"
  - link:
      icon: "fa-brands fa-telegram"
      text: "{{vars.I18n['Telegram']}}"
      url: "https://t.me/pslvirginia"
      alt: "Telegram"
      title: "Telegram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-signal-messenger"
      text: "{{vars.I18n['Signal']}}"
      url: "https://signal.group/#CjQKINr4fya6aLpVe5SUMzl9Ao0nDFnrQUYquoB29Dk9-h4_EhB1VF9Chvf_OJ3jGiYsh5tS"
      alt: "Signal"
      title: "Signal"
      target: "_blank"




# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
#socials:
#  - social:
#      icon: "fa-brands fa-instagram"
#      url: "https://www.instagram.com/rvaliberationcenter/"
#      title: "Instagram"
#      alt: "Instagram"
#      target: "_blank"

footer: >
  {{ vars.I18n['script'] }}

copyright: >
  📍 Located at 409 Brook Rd, Richmond, VA | Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a> 🦋
